# Generated by Django 6.0.1 on 2026-05-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0006_resume_ai_recommended_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI-generated match score', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='recruiter_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
