# Generated by Antigravity assistant

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_match_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='job_applications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source_type',
            field=models.CharField(
                choices=[('APPLICATION', 'Application'), ('RECRUITER_UPLOAD', 'Recruiter Upload')],
                default='APPLICATION',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Candidate tags for filtering'),
        ),
    ]
