# Generated by Django 6.0.1 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_address_company_email_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_document',
            field=models.FileField(blank=True, help_text='Uploaded official business registration / incorporation certificate', null=True, upload_to='verification/company_docs/'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='National Tax Number (NTN), EIN, or Business Registration ID', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text='Company business verification status', max_length=20),
        ),
    ]
