# Generated by Django 6.0.1 on 2026-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_registration_document_company_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='document_type',
            field=models.CharField(blank=True, choices=[('secp', 'SECP Certificate of Incorporation'), ('ntn', 'NTN Certificate (FBR)')], default='', help_text='Type of legal registration document provided', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason provided by admin if registration was rejected'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_document',
            field=models.CharField(blank=True, default='', help_text='Cloudflare R2 storage key / path for company verification document', max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='National Tax Number (NTN), SECP CUIN, or Business Registration ID', max_length=100),
        ),
    ]
