# Generated by Django 6.0.1 on 2026-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_cleaned_text_education_experience_resumeskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_category_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
