# Generated by Django 6.0.1 on 2026-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_ai_category_scores_resume_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_recommended_certifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
