# Generated by Django 6.0.1 on 2026-03-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='applicant', help_text='Role of the user for access control', max_length=20),
        ),
    ]
