# Generated by Django 6.0.1 on 2026-08-16 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    roles = ['admin', 'company_admin', 'recruiter', 'applicant']
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


def remove_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    roles = ['admin', 'company_admin', 'recruiter', 'applicant']
    Role.objects.filter(name__in=roles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='users.role')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.RunPython(create_default_roles, reverse_code=remove_default_roles),
    ]

