# Generated by Django 6.0.1 on 2026-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_user_role_fk_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('recruiter', 'Recruiter'), ('company_admin', 'Company Admin'), ('admin', 'Admin')], default='applicant', max_length=20),
        ),
    ]
