# Generated by Django 6.0.1 on 2026-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_image',
            field=models.CharField(blank=True, default='', help_text='Cloudflare R2 storage key for CNIC image', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic_number',
            field=models.CharField(blank=True, default='', help_text='CNIC / Identity Document Number', max_length=25),
        ),
    ]
