# Generated by Django 6.0.1 on 2026-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_image',
            field=models.ImageField(blank=True, help_text='Uploaded CNIC / Identity Document photo', null=True, upload_to='verification/cnic/'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnic_number',
            field=models.CharField(blank=True, default='', help_text='National Identity Card (CNIC / ID) Number', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text='Identity document verification status', max_length=20),
        ),
    ]
